[broker]
granularity = 5

[clientManager]
runtime = 10 # runtime of the experiments in min, starts counting at starttime (provided as argv)
offset = 1 # startup offset between individual clients in sec

    [clientManager.Weihnachtsmann]
    index = 1
    count = 100

    [clientManager.Schokoladenbonbon]
    index = 101
    # count = 200 -> not valid as count field is missing

[client]
geofenceSize = 0.1 # in degree
payloadSize = 10000 # in byte
