[broker]
granularity = 5
messageProcessors = 1

# Configuration related to the moving client experiments
[brokerMachine]
address = "tcp://localhost"
port = 5559

[clientManager]
runtime = 1 # runtime of the experiments in min, starts counting at starttime (provided as argv)
offset = 1 # startup offset between individual clients in sec

    [clientManager.Weihnachtsmann]
    index = 1
    count = 10

    [clientManager.Schokoladenbonbon]
    index = 101
    # count = 200 -> not valid as count field is missing

[client]
geofenceSize = 0.1 # in degree
payloadSize = 10000 # in byte
