# server information
[server]
brokerId = "Cloud"
port = 5560
granularity = 5
messageProcessors = 2

[server.mode]
name = "disgb_subscriberMatching"
#    name = "disgb_publisherMatching"
brokerAreaFilePath = "GeoBroker-Server/src/main/resources/jfsb/disgb_jfsb.json"
brokerCommunicators = 2

