# server information
[server]
brokerId = "Paris"
port = 5560
granularity = 5
messageProcessors = 2

    [server.mode]
    name = "disgb_subscriberMatching"
    brokerAreaFilePath = "GeoBroker-Server/src/main/resources/jfsb/disgb_jfsb.json"
    brokerCommunicators = 2

